### ISSUE TITLE
AdminController -> UserController

### ISSUE THREAD

**Issue by MacDada** [dudekm/blog#1]
Proponuję nie nazywać tego kontrolerem „adminowym”, tylko po prostu „użytkownikowym”. Podobnie widok.

**Comment by dudekm** [comment]
zrobione :)

**Comment by MacDada** [comment]
@dudekm Nie ma commita, to nie jest zrobione :P

**Comment by MacDada** [comment]
@dudekm OK: https://github.com/dudekm/blog/commit/3c8ce7facc1354e06df1d7149ee5cc755ffd43b8

**Comment by MacDada** [comment]
@dudekm Zobacz, że jak dałem linka do tego ISSUE przy commicie, to automatycznie też się tutaj pojawiło info:

https://github.com/dudekm/blog/commit/3c8ce7facc1354e06df1d7149ee5cc755ffd43b8#commitcomment-10606478

Więc jak puszczasz commita, to na Githubie daj w nim komentarz, do którego ISSUE dany commit się odnosi.
