### ISSUE TITLE
Przestrzenie nazw

### ISSUE THREAD

**Issue by MacDada** [dudekm/blog#10]
Ty masz klasę `User`, każdy inny kod może mieć klasę `User` – jakbyś chciał wymieszać swój kod z jakąś biblioteką, to powstanie konflikt nazw.

Rozwiązaniem są przestrzenie nazw (czyli po prostu klasy w kategoriach).
Zmień, żeby Twoje klasy były w przestrzeni `Dudekm\Blog` (wg konwencji: nazwa dostawcy + nazwa projektu + nazwa klasy).

Czyli np `Dudekm\Blog\User`.

Do przeczytania: https://php.net/manual/pl/language.namespaces.php

todo:

- [x] na początek tylko klasa `User`
- [x] potem wszystkie inne klasy i interface'y

**Comment by dudekm** [comment]
@MacDada 
klasa ma wyglądać tak:

<?php

namespace Dudekm\Blog;

class User
....

a wywoładnie w PdoUserRepository:
    private function createUser(array $userData)
    {
        $user = new Dudekm\Blog\User($userData['username'], $userData['password'], $userData['email'], $userData['id']);
        return $user;
    }

Jeśli tak to wywala mi błąd:
Fatal error: Class 'User' not found in C:\xampp\htdocs\blog\controller\userController.php on line 38

**Comment by MacDada** [comment]
Tak, deklaruj na tej zasadzie.

Jak chcesz użyć klasy, to albo musisz zrobić `use Przestrzen\Klasa` albo odwołać się w kodzie bezpośrednio do `\Przestrzen\Klasa` (bez use konieczny backslash).

**Comment by MacDada** [comment]
Zacznij od jednej klasy, jak zadziała, bierz kolejne – bo jak wszystko na raz zaczniesz zmieniać, to nie dojdziesz gdzie masz błąd.

**Comment by dudekm** [comment]
@MacDada poszedł commit ale nie działa... :/

**Comment by MacDada** [comment]
Wszystkie odwołania do klasy `User` muszą teraz uwzględniać przestrzenie.

**Comment by dudekm** [comment]
@MacDada
https://github.com/dudekm/blog/commit/0f4b14fe202de9320b5ea4d55d7d538be62fcb5b
