### ISSUE TITLE
Katalog publiczny

### ISSUE THREAD

**Issue by MacDada** [dudekm/blog#11]
Jeśli wszystkie pliki są w katalogu publicznym, to można się do nich dostać po prostu z przeglądarki. Nawet do plików z klasami.

Część plików nie powinna być dostępna publicznie, więc utwórz katalog „web” i w nim trzymaj tylko to co ma być dostępne przez przeglądarkę. Reszta plików powinna być katalog wyżej.

Przykładowe ścieżki:

`/web/index.php` – plik dostępny z przeglądarki
`/web/admin/index.php` – plik dostępny z przeglądarki
`/boot.php` – plik NIEdostępny z przeglądarki
`/model/User.php` – plik NIEdostępny z przeglądarki

ToDo:

- [x] utwórzyć katalog `web`
- [x] przenieść do niego pliki publiczne
- [x] poprawić ścieżki ładowania plików
- [x] skonfigurować serwer, żeby wskazywał na `web`

**Comment by dudekm** [comment]
@MacDada rozumiem, że w pliku hosts należy ustawić aby po wpisaniu adresu app.dev odpalał się plik blog/web/index.php ?

**Comment by dudekm** [comment]
@MacDada zrobione

**Comment by MacDada** [comment]
@dudekm yep
