### ISSUE TITLE
Klasy w przestrzeniach PSR-0

### ISSUE THREAD

**Issue by MacDada** [dudekm/blog#12]
Po ukończeniu tych dwóch:

* https://github.com/dudekm/blog/issues/10
* https://github.com/dudekm/blog/issues/11

Do przeczytania: http://www.php-fig.org/psr/psr-0/

W katalogu głównym utwórz katalog `src`, w środku katalogi tak jak przestrzenie nazw.

Czyli np klasa `Dudekm\Blog\UserRepository` ma być pod ścieżką `/src/Dudekm/Blog/UserRepository.php`

Zwracaj uwagę na wielkości liter i PSR–owe konwencje (np nazwy klas `PascalStyle`).

ToDo:

- [x] Przenieść klasy do src wg konwencji PSR-0
- [x] Poprawić ładowanie plików (nadal ręczne, automatyczne w kolejnym issue)

**Comment by dudekm** [comment]
@MacDada O jakie klasy chodzi? User i UserRepository czy klasami nadal uznajemy też kontroler, warstwy modelu i widok?

**Comment by MacDada** [comment]
wszystkie klasy
