### ISSUE TITLE
Struktura plików

### ISSUE THREAD

**Issue by MacDada** [dudekm/blog#15]
Utwórz katalogi i przenieś odpowiednio pliki do przestrzeni:

* `\Dudekm\Blog\Controller\`
* `\Dudekm\Blog\Entity` (tutaj encje jak „User” i repozytoria)
* `\Dudekm\Blog\View`

Takie jakby kategorie, żeby nie robić wszystkiego w jednym katalogu.

**Comment by dudekm** [comment]
@MacDada klasa z wyjątkiem UserNotFoundException powinna być w folderze Entity ?

**Comment by MacDada** [comment]
@dudekm tak

**Comment by MacDada** [comment]
:+1:
