### ISSUE TITLE
wszędzie: bindowanie zmiennych w SQLach

### ISSUE THREAD

**Issue by MacDada** [dudekm/blog#18]
zamiast sklejania z potencjalnym sql injection

**Comment by MacDada** [comment]
@dudekm :+1:  Jest OK, ale dla nauki zrób jeszcze gdzieś bindowanie przez przekazanie zmiennych do `execute()`

**Comment by dudekm** [comment]
@MacDada 
https://github.com/dudekm/blog/commit/1147b69b25f2765f7a77b9cd2574535329ddbad0

**Comment by MacDada** [comment]
:+1:
