### ISSUE TITLE
poprawny HTML5

### ISSUE THREAD

**Issue by MacDada** [dudekm/blog#19]
wszystkie strony mają się prawidłowo walidować w html5

**Comment by dudekm** [comment]
@MacDada 
https://github.com/dudekm/blog/commit/d46c34d9771123012a40534dc0ef48ed041c3517
https://github.com/dudekm/blog/commit/fe6baf2a9459a08f70d7937e54f87cc9d4def296

**Comment by MacDada** [comment]
@dudekm Kontroler teraz wywołuje dwie metody z widoku – renderujące treść strony i renderujące szablon.

Niech wywołuje tylko jedną metodę, to widok powinien zadbać o to, żeby mieć szablon.

**Comment by MacDada** [comment]
:+1:
