### ISSUE TITLE
Dodawanie użytkowników

### ISSUE THREAD

**Issue by MacDada** [dudekm/blog#2]
Na początek:

- [x] Akcja kontrolera, która będzie służyła do tworzenia użytkowników, np `create()`.
- [x] Dodaj odpalanie tej akcji we frontcontrollerze adminowym
- [x] Wyświetlaj w niej formularz dodawania użytkownika (`POST`owy)
- [x] Rozróżniaj czy przyszedł `POST` – jeśli nie to wyświetlaj formularz, jeśli tak to poniższe:
- [x] W akcji kontrolera odczytaj parametry `POSTa` i utwórz na ich podstawie obiekt użytkownika
- [x] W repozytorium utwórz metodę `save(User $user)` – która zapisze obiekt do bazki
- [x] W akcji kontrolera użyj repozytorium, żeby ten obiekt użytkownika zapisać do bazki
- [x] Na koniec kontroler nich zrobi redirect do wyświetlenia nowo–utworzonego użytkownika
- [x] Zabezpieczyć zapisywanie przed SQL–Injection
- [x] Zapis do bazki: obsługa błędów: rzuć wyjątkiem, jeśli nie udało się zapisać

**Comment by dudekm** [comment]
@MacDada rozróżnianie czy przyszedł $_POST, czy formularze nie są puste itp. robię w kontrolerze?

**Comment by MacDada** [comment]
tak

**Comment by MacDada** [comment]
@dudekm Nie odfajkowywuj, że zrobione póki nie widzę kodu i nie potwierdzę, że jest OK :P

**Comment by dudekm** [comment]
@MacDada ok :)
