### ISSUE TITLE
Obiekt reprezentujący żądanie HTTP

### ISSUE THREAD

**Issue by MacDada** [dudekm/blog#22]
Zamiast korzystać w kontrolerze z superglobali typu `$_GET`, utwórz obiekt reprezentujący żądanie HTTP.

- [x] klasa `Request`
- [x] posiada metody dostępowe do zmiennych superglobalnych (np `$request->getPost('klucz')` zwraca `$_POST['klucz']`, `$request->getGet('klucz')` zwraca `$_GET['klucz']`)
- [x] przekazuj obiekt `Request` jako argument akcji kontrolerów, żeby kontrolery nie korzystały z superglobali

**Comment by dudekm** [comment]
https://github.com/dudekm/blog/commit/9ea0c0eef350eab83707d4c27883960691b49e2e

**Comment by dudekm** [comment]
@MacDada https://github.com/dudekm/blog/commit/59f700cb1ae3a25ede23c5d24bb2339435eb97ab

**Comment by MacDada** [comment]
:+1:
