### ISSUE TITLE
Wyświetlanie użytkowników nie powinno być tylko dla adminów

### ISSUE THREAD

**Issue by MacDada** [dudekm/blog#24]
Niech zwykłe `index.php` pozwala wyświetlać użytkowników, zamiast adminowego.

**Comment by dudekm** [comment]
@MacDada Dlaczego wszyscy mają widzieć użytkowników, maile i hasła?

**Comment by MacDada** [comment]
No to bez mejli i haseł, samo info ;-)

Ogólnie propozycja funkcjonalności – haseł to i admini nie powinni widzieć
