### ISSUE TITLE
jeden frontcontroller

### ISSUE THREAD

**Issue by MacDada** [dudekm/blog#26]
Po co dodatkowy fontcontroller dla admina? Niech wszystko idzie przez jeden `index.php`, żeby uniknąć kopiuj–wklejkowania.

_Plus później łatwiej będzie przerobić na „ładne urle” bez plików php w adresie_

**Comment by dudekm** [comment]
@MacDada https://github.com/dudekm/blog/commit/b5c924e02ce3012eb235a9af9efc616e0be2aa53

**Comment by MacDada** [comment]
:+1:
