### ISSUE TITLE
Zduplikowane wyjątki nieznalezionych encji

### ISSUE THREAD

**Issue by MacDada** [dudekm/blog#30]
Wywal te dwa co są teraz i zrób jeden `EntityNotFound` – bo im więcej encji, tym więcej miałbyś (niepotrzebnie rozróżnialnych) klas wyjątków.

**Comment by dudekm** [comment]
@MacDada https://github.com/dudekm/blog/commit/ef45572a0eec76b2384dc2205cec5146e37c8919

**Comment by dudekm** [comment]
@MacDada Usunąłem rzucanie wyjątków, zastąpiłem to NULLami
https://github.com/dudekm/blog/commit/64113b6b1fd0f4b70f0986f9ea32302006eb32c4
